const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
  close: () => ipcRenderer.send('window-close'),
  minimize: () => ipcRenderer.send('window-minimize'),
  maximize: () => ipcRenderer.send('window-maximize'),
  openPanel: () => ipcRenderer.send('open-panel'),
  dragWindow: (dx, dy) => ipcRenderer.send('window-drag', { dx, dy }),
  setInteractive: (v) => ipcRenderer.send('set-interactive', v),
  relaySend: (data) => ipcRenderer.send('relay-send', data),
  onRelayMessage: (callback) => {
    const handler = (event, data) => {
      window.dispatchEvent(new CustomEvent('pety-relay', { detail: data }));
      callback(data);
    };
    ipcRenderer.on('relay-message', handler);
  },
  getRelayStatus: () => ipcRenderer.invoke('get-relay-status'),
  getWindows: () => ipcRenderer.invoke('get-windows'),
  startVoiceServer: () => ipcRenderer.send('start-voice-server'),
  stopVoiceServer: () => ipcRenderer.send('stop-voice-server'),
  getDesktopBackground: () => ipcRenderer.invoke('take-screenshot', { width: 1920, height: 1080 }),
  getLocalChat: (limit) => ipcRenderer.invoke('get-local-chat', limit),
  searchChat: (query) => ipcRenderer.invoke('search-chat', query),
  uploadChat: (url) => ipcRenderer.invoke('upload-chat', url),
  downloadChat: (url) => ipcRenderer.invoke('download-chat', url),
  pickFile: () => ipcRenderer.invoke('pick-file'),
  saveVoice: (base64, ext) => ipcRenderer.invoke('save-voice', base64, ext),
  takeScreenshot: () => ipcRenderer.invoke('take-screenshot', { width: 800, height: 600 }),
  cacheTtsAudio: (text, base64) => ipcRenderer.send('cache-tts-audio', { text, base64 }),
  getCachedTts: (text) => ipcRenderer.invoke('get-cached-tts', text),
  getVoiceConfig: () => ipcRenderer.invoke('get-voice-config'),
  saveVoiceConfig: (cfg) => ipcRenderer.invoke('save-voice-config', cfg),
  saveVoiceFavorite: (data) => ipcRenderer.invoke('save-voice-favorite', data),
  getVoiceFavorites: () => ipcRenderer.invoke('get-voice-favorites'),
  deleteVoiceFavorite: (id) => ipcRenderer.invoke('delete-voice-favorite', id),
  playVoiceFavorite: (id) => ipcRenderer.invoke('play-voice-favorite', id),
  callResponse: (response) => ipcRenderer.send('call-response', response),
  petWalk: (data) => ipcRenderer.send('pet-walk', data),
  petStopWalk: () => ipcRenderer.send('pet-stop-walk'),
  petAutoWalkToggle: (enabled) => ipcRenderer.send('pet-auto-walk-toggle', enabled),
  petPhysicsToggle: (enabled) => ipcRenderer.send('pet-physics-toggle', enabled),
  ttsGenerate: (text) => ipcRenderer.invoke('tts-generate', text),
  getApiConfig: () => ipcRenderer.invoke('get-api-config'),
  saveApiConfig: (cfg) => ipcRenderer.invoke('save-api-config', cfg),
  apiChat: (data) => ipcRenderer.send('api-chat', data),
  getTokenStats: () => ipcRenderer.invoke('get-token-stats'),
  resetTokenStats: () => ipcRenderer.invoke('reset-token-stats'),
  getTokenBreakdown: () => ipcRenderer.invoke('get-token-breakdown'),
  getMemories: (opts) => ipcRenderer.invoke('get-memories', opts),
  addMemory: (data) => ipcRenderer.invoke('add-memory', data),
  updateMemory: (data) => ipcRenderer.invoke('update-memory', data),
  deleteMemory: (id) => ipcRenderer.invoke('delete-memory', id),
  resolveMemory: (id) => ipcRenderer.invoke('resolve-memory', id),
  searchMemories: (q) => ipcRenderer.invoke('search-memories', q),
  memoryStats: () => ipcRenderer.invoke('memory-stats'),
  pickMemoryFile: () => ipcRenderer.invoke('pick-memory-file'),
  testMemoryConnection: (url) => ipcRenderer.invoke('test-memory-connection', url),
});
